[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
tokio = { version = "1", features = ["full"] } # Optional for async runtime
serde = { version = "1.0", features = ["derive"] } # For JSON handling
serde_json = "1.0"
